import type { CapacitorConfig } from "@capacitor/cli";

/**
 * Stretchline is a TanStack Start SSR app — it cannot be bundled as a static
 * web app inside the Capacitor WebView. The native shell instead loads the
 * hosted web app via `server.url`. The `dist/` folder (generated by
 * `npm run cap:build`) is only a minimal fallback shell so that `cap sync`
 * succeeds and the app has something to show if the device is fully offline.
 *
 * To point the shell at a different deployment (e.g. preview build), set
 * the `server.url` value below before running `npm run cap:sync`.
 */
const config: CapacitorConfig = {
  appId: "app.lovable.stretchline",
  appName: "Stretchline",
  webDir: "dist",
  server: {
    url: "https://stretch-streak-studio.lovable.app",
    cleartext: false,
    androidScheme: "https",
    iosScheme: "https",
  },
  ios: {
    contentInset: "always",
  },
  android: {
    allowMixedContent: false,
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 1500,
      backgroundColor: "#0B0B14",
      showSpinner: false,
    },
    StatusBar: {
      style: "DARK",
      backgroundColor: "#0B0B14",
    },
  },
};

export default config;
